// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int above = 0;
		int under = 0; 
		for ( int t = 0; t < N; t++) {
			double randomValue = Math.random();
				if ( randomValue > 0.5 ) above++;
				else under++; 		
		}
		if (above == 0 || under == 0 ){
			System.out.println( "> 0.5: " + above + " times");
			System.out.println( "<= 0.5: " + under + " times");
		}
		else {
		double ratio = (double) above/under;
		System.out.println( "> 0.5 " + above + " times");
		System.out.println( "<= 0.5: " + under + " times");
		System.out.println("ratio: " + ratio );
		}
		

	}
}
